### ISSUE TITLE
Bug save_substitute

### ISSUE THREAD

**Issue by etiennody** [etiennody/purchoice#9]
Initially, I have Pylint warning me with : "Value 'self.choice' is unsubscriptable"... in controller.py
If I run the app even... At the time of backup, I have :" Voulez-vous sauvegarder votre substitut ? [o/n] o
Traceback (most recent call last):
  File "app.py", line 7, in <module>
    Controller().run()
  File "/Volumes/Workspace/oc/P5/purchoice/controller.py", line 48, in run
    self.db.save_substitute(self.choice[0], self.choice[1])
  File "/Volumes/Workspace/oc/P5/purchoice/purchoice_database.py", line 139, in save_substitute
    self.session.commit()
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1036, in commit
    self.transaction.commit()
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 503, in commit
    self._prepare_impl()
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 482, in _prepare_impl
    self.session.flush()
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2496, in flush
    self._flush(objects)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2637, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    flush_context.execute()
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute
    persistence.save_obj(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj
    _emit_insert_statements(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/orm/persistence.py", line 1135, in _emit_insert_statements
    result = cached_connections[connection].execute(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 984, in execute
    return meth(self, multiparams, params)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1097, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1287, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1485, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1247, in _execute_context
    self.dialect.do_execute(
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/cursors.py", line 168, in execute
    query = self.mogrify(query, args)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/cursors.py", line 147, in mogrify
    query = query % self._escape_args(args, conn)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/cursors.py", line 127, in _escape_args
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/cursors.py", line 127, in <dictcomp>
    return {key: conn.literal(val) for (key, val) in args.items()}
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/connections.py", line 467, in literal
    return self.escape(obj, self.encoders)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/connections.py", line 460, in escape
    return converters.escape_item(obj, self.charset, mapping=mapping)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/converters.py", line 27, in escape_item
    val = encoder(val, mapping)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/converters.py", line 118, in escape_unicode
    return u"'%s'" % _escape_unicode(value)
  File "/Users/jodyetienne/.local/share/virtualenvs/purchoice-c9mGGwQr/lib/python3.8/site-packages/pymysql/converters.py", line 73, in _escape_unicode
    return value.translate(_escape_table)
AttributeError: 'Product' object has no attribute 'translate' "

I've done some research on stackoverflow, I still haven't found anything conclusive or I haven't looked in the right place :\ Otherwise, on developpez.com, I tried a typical solution: "# self.choice = self.choice.__getitem__ = lambda item: item"...Mais erreur avec :Traceback (most recent call last):  File "app.py", line 7, in <module>
    Controller().run()
  File "/Volumes/Workspace/oc/P5/purchoice/controller.py", line 48, in run
    self.db.save_substitute(self.choice[0], self.choice[1])
TypeError: 'function' object is not subscriptable

If you've got a hint about that, I'll be interested.

**Comment by etiennody** [comment]
Fix the issue by modifying the Favorite model depending on Product model + modifying args in save_substitute method in purchoice_database.py & controller.py…
